[package]
name = "rust"
version = "0.1.0"
authors = ["Christoph Stelz <mail@ch-st.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libpulse-simple-binding = "2.15.0"
libpulse-binding = "2.15.0"
